config/routes.rb
Rails.application.routes.draw do
	root 'admin_reports#show_project_pie_chart'	
	devise_for :users
	resources :projects do 
		resources :tasks
	end
	get '/list_user_tasks', to: 'tasks#list_user_tasks', as: 'list_user_tasks'
	post '/update_task_status', to: 'tasks#update_task_status'
	get '/show_project_pie_chart', to: 'admin_reports#show_project_pie_chart', as: 'show_project_pie_chart'
	get '/get_project_pie_data', to: 'admin_reports#get_project_data'
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks
	has_many :project_developers
	has_many  :users, through: :project_developers

	def self.show_project_report(project_ids)
		UserTask.joins("INNER JOIN tasks as t on t.id = user_tasks.task_id INNER JOIN projects as pr on pr.id = t.project_id")
		.select("pr.name, sum( CASE WHEN user_tasks.status='NOT_STARTED' THEN 1 ELSE 0 end) as not_started, sum(CASE WHEN user_tasks.status = 'IN_PROGRESS' THEN 1 ELSE 0 END) as in_progress, sum(case when user_tasks.status = 'DONE' THEN 1 ELSE 0 END) as done").where("t.project_id IN (?)",project_ids).group("pr.name")
	end

end

app/models/project_developer.rb
class ProjectDeveloper < ActiveRecord::Base
	belongs_to  :project
	belongs_to	:user
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :user_tasks
	has_many :users, through: :user_tasks



  def self.get_task_by_status(task_status, user_id)
    joins('INNER JOIN user_tasks as ut ON ut.task_id = tasks.id').where("ut.status =? and ut.user_id = ?", task_status, user_id)
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role
  has_many	:project_developers
  has_many	:projects, through: :project_developers
  has_many  :user_tasks
  has_many  :tasks, through: :user_tasks

  class << self

  	# Get all developers 
  	def get_all_developers
  		where(role_id: DEVELOPER_ROLE)
  	end

  end

  # Check if user is admin
  def is_admin?
    self.role_id.present? && ADMIN_ROLE_ID == self.role_id
  end
  
  def get_developer_tasks
      Task.joins("INNER JOIN user_tasks AS ut ON ut.task_id = tasks.id ")
      .select("ut.status as ut_status, ut.id as ut_id, tasks.name, tasks.description")
      .where("ut.user_id = ?", self.id)
  end

  def developer_status_report
    #User.joins('INNER JOIN user_tasks as ut ON ut.user_id = users.id INNER JOIN tasks as t ON t.id= ut.task_id').select("ut.status as ut_status, users.name as u_name, t.name").where("users.role_id": DEVELOPER_ROLE).order("ut.status")
    User.joins('INNER JOIN user_tasks as ut ON ut.user_id = users.id').select("users.id, ut.status as ut_status, users.name as u_name").where("users.role_id": DEVELOPER_ROLE).order("ut.status").group("ut.status, users.id")
    #User.includes(:user_tasks).includes(:tasks)
  end


end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
	belongs_to :user
	belongs_to	:task
end

app/controllers/admin_reports_controller.rb
class AdminReportsController < ApplicationController

	before_filter :check_admin
	
	# Get Pie chart data of projects
	def get_project_data
		project_data = Project.show_project_report(Project.all.collect(&:id))
		respond_to do |format|
			format.json { render json: {'data': project_data.to_json}}	
		end
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  # Check admin 
  def check_admin
    unless current_user.is_admin? 
      return redirect_to list_user_tasks_path
    end
  end
  
  # After sigin redirect to specfic path
  def after_sign_in_path_for(resource)
  	if current_user.is_admin?
      show_project_pie_chart_path
  	else
  		list_user_tasks_path
  	end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :check_admin
  respond_to :html

  def index
    @projects = Project.all
    respond_with(@projects)
  end

  def show
    @developers = User.get_all_developers
    respond_with(@project)
  end

  def new
    @project = Project.new
    @developers = User.get_all_developers
    respond_with(@project)
  end

  def edit
    @developers = @project.users
  end

  def create
    @project = Project.new(project_params)
    @project.save
    params[:developers].each do |id|
      @project.project_developers.create(user_id: id)
    end
    respond_with(@project)
  end

  def update
    @project.update(project_params)
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end


  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	before_action :set_project, only: [:new, :index, :create]
	before_action :check_admin, only: [:new, :index, :create]	

	# Create new task
	def new
		@developers = @project.users
	end

	# Create user tasks
	def create
		@task = @project.tasks.create(task_params)
		params[:developers].each do |id|
			@task.user_tasks.create(user_id: id)
		end
		redirect_to action: "index"
	end

	# Get all tasks
	def index
	end

	# Delete task 
	def destroy
		@task = Task.find_by_id(params[:id])
		@task.destroy
		redirect_to action: "index"
	end

	# List tasks of users
	def list_user_tasks
		@tasks = current_user.get_developer_tasks
	end

	def update_task_status
		if params[:task_id].present? && params[:task_status].present?
			task = UserTask.find_by_id(params[:task_id])
			task.update_attributes(status: params[:task_status]) if task.present?
			msg = 'Status updated'
		else
			msg = 'Task not found'
		end
		respond_to do |format|
			format.json { render json: {'response': msg}.to_json}	
		end
	end


	private

		def set_project
			@project = Project.find_by_id(params[:project_id])
		end

		def task_params
			params.require(:task).permit(:name, :description)
		end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin_reports/show_project_pie_chart.html.erb
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<%= javascript_include_tag 'pie_chart'%>
<table class="columns margin-top-10 ">
      <tr class="table-row">
      </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectMgt</title>
  <%= stylesheet_link_tag   'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/partials/header'%>
<div class="container-fluid text-center">    
	<div class="row content">
		<div class="col-sm-12 text-left"> 
			<%= yield %>
		</div>	
	</div>	
</div>
</body>
</html>

app/views/layouts/partials/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="/">ProjectMgt</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.is_admin? %>  
            <li><%= link_to 'List Projects', projects_path, class: 'font-size-15' %></li>
            <li><%= link_to 'Create New Project', new_project_path, class: 'font-size-15' %></li>
            <li><%= link_to 'Project Status', show_project_pie_chart_path, class: 'font-size-15' %></li>
          <% end %>  
            <li> <%= link_to(current_user.email) if current_user.present? %> </li>
            <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
        <% else %>
            <li>
              <%= link_to('Login', new_user_session_path)  %>  
            </li>
        <% end %>
        <li>
        <div class="dropdown margin-top-10">
          <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">List Of Users
          <span class="caret"></span></button>
            <ul class="dropdown-menu">
              <li><a href="#">admin@gmail.com - 123456</a></li>
              <li><a href="#">developer1@gmail.com - 123456 </a></li>
              <li><a href="#">developer2@gmail.com - 123456</a></li>
              <li><a href="#">developer3@gmail.com - 123456</a></li>
              <li><a href="#">developer4@gmail.com - 123456</a></li>
          </ul>
        </div>
      </li>
      </ul>
    </div>
  </div>
</nav>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="fields">
      <%= f.label :developers%>
      <%=select_tag "developers", options_from_collection_for_select(@developers, "id", "email"),  multiple: true, class: 'chosen-select form-control' %>
    </div><br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="5">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td>
            <%= link_to 'Create Task', new_project_task_path(project), class: 'link-design btn-sm btn-primary' %>
            &nbsp; 
            <%= link_to 'Show Task', project_tasks_path(project), class: 'link-design btn-sm btn-primary' %>
            &nbsp; 
            <%= link_to 'Edit', edit_project_path(project), class: 'link-design btn-sm btn-primary' %>
            <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' },class: 'link-design btn-sm btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path, class: 'btn btn-primary link-design' %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_form.html.erb
<%= form_for( [@project, @project.tasks.build]) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="fields">
      <%= f.label :developers%>
      <%=select_tag "developers", options_from_collection_for_select(@developers, "id", "email"),  multiple: true, class: 'chosen-select form-control' %>
    </div><br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/index.html.erb
<h1>Listing Task Of <%= @project.name %></h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Developer Names</th>
    </tr>
  </thead>

  <tbody>
    <% count = 0%>
    <% @project.tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.users.collect(&:name).join(', ')%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_project_task_path(@project), class: 'link-design btn btn-primary' %>

app/views/tasks/list_user_tasks.html.erb
<h4 class="alert alert-info">Alloted Tasks</h4>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Sr.No</th>
      <th>Name</th>
      <th>Description</th>
      <th>Change Status</th>
    </tr>
  </thead>

  <tbody>
    <% count = 0%>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= count += 1%></td>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= select_tag 'Change Status', options_for_select(TASK_STATUS, task.ut_status), {class: 'form-control update_task_status width-50per', "data-id": task.ut_id }%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tasks/new.html.erb
<h1>New Project Task</h1>

<%= render 'form' %>